version: '2'

services:
  php8.0:
    container_name: php8.0
    build: manifests/dockerfiles/php8.0
    restart: always
    expose:
      - "9002"
    volumes:
      - ../:/www
    working_dir: /www
    environment:
      - TZ=Asia/Shanghai
  proxy:
    container_name: proxy_nginx
    build: ./manifests/dockerfiles/proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./manifests/config/proxy/conf.d:/etc/nginx/conf.d
      - ./manifests/config/proxy/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - php8.0
    working_dir: /etc/nginx
    links:
      - php8.0
      - mysql
      - redis
    environment:
      - TZ=Asia/Shanghai
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:8.0.18
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./manifests/docker_data/var_lib_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./manifests/docker_data/var_lib_redis:/data
    command: redis-server --appendonly yes
    environment:
      - TZ=Asia/Shanghai