version: '2'

services:
  etcd:
    container_name: etcd
    image: bitnami/etcd:3
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - dev
    ports:
      - 2379:2379
      - 2380:2380
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:8.0.18
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./manifests/docker_data/var_lib_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=M5xXGPdGWxjr5TQ
      - TZ=Asia/Shanghai
  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./manifests/docker_data/var_lib_redis:/data
    command: redis-server --appendonly yes --requirepass "M5xXGPdGWxjr5TQ"
    environment:
      - TZ=Asia/Shanghai